chain_width = 60
empty_item_single_line = true
enum_discrim_align_threshold = 30
format_strings = true
imports_granularity = "Crate" 
imports_indent = "Block"
imports_layout = "HorizontalVertical"
max_width = 100
normalize_comments = true
reorder_imports = true
struct_field_align_threshold = 30
struct_lit_single_line = true
tab_spaces = 8 
use_field_init_shorthand = true
where_single_line = true
wrap_comments = true

